owner: discord-creator
repo: upptime

sites:
  - name: MonitoRSS-Ambler
    url: $MONITORSS_AMBLER
  - name: MonitoRSS-Cord
    url: $MONITORSS_CORD
  - name: MonitoRSS-Music
    url: $MONITORSS_MUSIC
  - name: MonitoRSS-Tech
    url: $MONITORSS_TECH
  - name: MonitoRSS-Journalism
    url: $MONITORSS_TECH

status-website:
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Discord Bots Status
  introTitle: "**Upptime** for Discord Bots"
  introMessage: 디스코드 봇 모니터
